### ISSUE TITLE
Clean up repository structure

### ISSUE THREAD

**Issue by jhanca-robotecai** [RobotecAI/o3de-genai-gems#106]
Repo: o3de-gen-ai-gems
- Framework
  - GenAIFramework
  - GenAIMockVendor
- Features
  - SceneGeneration
- Vendors
  - AmazonBedrock
  - HttpProviderBundle

What about this naming (this would simplify things)?

_Originally posted by @adamdbrw in https://github.com/RobotecAI/ai-core-gem/pull/91#pullrequestreview-2052243083_

**Comment by arturkamieniecki** [comment]
Done in #152
