### ISSUE TITLE
PR #138 follow up

### ISSUE THREAD

**Issue by jhanca-robotecai** [RobotecAI/o3de-genai-gems#148]
There were few questions raised in the review of #138:

Answer the questions by one or more PRs.
- [x] check if Async implementation for Python can be removed
- [x] add a tutorial about creating a PythonFeature
- [x] change the existing documentation to follow up the changes here (creating a cpp feature, information about inheritance and base classes)
- [x] check if all python scripts in `GenAIFramework/Editor/Scripts` are usable; remove the obsolete

**Comment by arturkamieniecki** [comment]
Steps 2 and 3 are done in #149.

**Comment by jhanca-robotecai** [comment]
^^ marking as done

**Comment by arturkamieniecki** [comment]
Step one done in: https://github.com/RobotecAI/o3de-genai-gems/pull/150.

As for step 4 every python script is an example script that is not used anywhere in the code, except the assistant.py script.
