### ISSUE TITLE
Remove anthropic model version field in configuration

### ISSUE THREAD

**Issue by adamdbrw** [RobotecAI/o3de-genai-gems#71]
Handle this by model selection on the list or otherwise specifically, and don't show it for other models, where the field is not applicable.

**Comment by jhanca-robotecai** [comment]
Model definitions change very quickly and adding anything other than an empty field would require constant changes in the codebase. There is a default, working, value in the field now. It can be changed by the user easily. Additionally, there is extensive documentation about setting these parameters and an issue to add even more details about it.
